=== sandra-1223/MCA-272-Web-Stack-Development-CAT-Test1/company_xsd.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="company">

<xs:complexType>
<xs:sequence>
<xs:element name="employee" maxOccurs="unbounded" minOccurs="0">
    <xs:complexType>
            <xs:sequence>
               <xs:element type="xs:string" name="empname"/>
               <xs:element type="xs:byte" name="empage"/>
               <xs:element type="xs:short" name="empsalary"/>
               <xs:element type="xs:string" name="empemailid"/>
               <xs:element type="xs:long" name="empphonenum"/>
               <xs:element type="xs:string" name="empdesignation"/>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="eid" use="optional"/>
    </xs:complexType>
</xs:element>
<element name="empsalary">
</xs:sequence>
</xs:complexType>

</xs:element>
</xs:schema>

=== sandra-1223/MCA-272-Web-Stack-Development-CAT-Test1/company_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="company_xsl.xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="company_xsd.xsd">
   
  <employee eid="101">
    <empname>Merin</empname>
    <empage>25</empage>
    <empsalary>13000</empsalary>
    <empemailid>101merinbaseline@gmail.com</empemailid>
    <empphonenum>9207571749</empphonenum>
    <empdesignation>Developer</empdesignation>
  </employee>

  <employee eid="102">
    <empname>Sherin</empname>
    <empage>32</empage>
    <empsalary>23000</empsalary>
    <empemailid>102sherinbaseline@gmail.com</empemailid>
    <empphonenum>9207571740</empphonenum>
    <empdesignation>Developer</empdesignation>
  </employee>

  <employee eid="103">
    <empname>Jerin</empname>
    <empage>24</empage>
    <empsalary>18000</empsalary>
    <empemailid>103jerinbaseline@gmail.com</empemailid>
    <empphonenum>9207671746</empphonenum>
    <empdesignation>Developer</empdesignation>
  </employee>
  
</company>
